### ISSUE TITLE
ssm-session does not show all instances

### ISSUE THREAD

**Issue by ztmr** [mludvig/aws-utils#4]
The `ssm-session` utility does not seem to list all available instances.

Running AWS CLI v2 `aws ssm get-inventory` gives me hundreds of instances while `ssm-session` utility shows only 13 (why not 10, 20, or so?).

Picking any instance not listed by `ssm-session` and using `ssm-session` to connect there is working fine. All of these are in the same region.

Could be API paging issue?

**Comment by mludvig** [comment]
Hi, quite likely paging and/or excluding terminated or managed instances. 

However `ssm-session` and other `ssm-*` wrappers are now maintained in a separate project: https://github.com/mludvig/aws-ssm-tools - check out if the version from there works better. I will remove `ssm-session` from here to avoid further confusion.
