### ISSUE TITLE
ssm-session link in README points to missing tool

### ISSUE THREAD

**Issue by fred-vogt** [mludvig/aws-utils#5]
[README.md#aws-utils-scripts](https://github.com/mludvig/aws-utils/blob/master/README.md#aws-utils-scripts) section has a broken link to:
  https://github.com/mludvig/aws-utils/blob/master/ssm-session

Perhaps should link to: https://github.com/mludvig/aws-utils/blob/master/ssm-session.README.md

**Comment by yosun** [comment]
https://github.com/mludvig/aws-ssm-tools 

similarly broken links link to your ssm-session tool on your blog @mludvig

**Comment by mludvig** [comment]
Fixed, thanks!
